#ifndef COMMONENUMS_GAMESCRIPT_H
#define COMMONENUMS_GAMESCRIPT_H

#include "CommonDefine.h"

BEGIN_NAMESPACE(GameScript)
enum MOVE_DIRECTION: char
{
    MOVE_LEFT,
    MOVE_TOP,
    MOVE_RIGHT,
    MOVE_BOTTOM
};

enum CTRL_SLOTS
{
    CTRL_SLOTS_0,
    CTRL_SLOTS_1,
    CTRL_SLOTS_2,
    CTRL_SLOTS_3,
    CTRL_SLOTS_4,
    CTRL_SLOTS_5,
    CTRL_SLOTS_6,
    CTRL_SLOTS_7,
    CTRL_SLOTS_8,
    CTRL_SLOTS_9,
    CTRL_SLOTS_10,
};
END_NAMESPACE

#endif // COMMONENUMS_GAMESCRIPT_H
